inputs:
  sky_alm: inputs/sky/example_sky_alms.npz
  beams_dir: inputs/beams
  rimo_file: inputs/RIMOs/RIMO_HFI_npipe5v16_symmetrized.fits
  mission_length: full
  pointings: inputs/pointings/pointing_
  flags: inputs/flags/flags_

detector_selection:
  channel: null
  detectors: []

resampling:
  coordinate_system: galactic
  center_pointing: false

nthreads: 0

convolution:
  lmax: 1024
  mmax: 16
  epsilon: 1.0e-5
  chunks: 1
  beam_normalization: unit_integral

map:
  nside: 512
  nest: false

output:
  output_dir: outputs
  output_prefix: pquick_demo
