inputs:
  sky_alm: inputs/sky/notebook_demo_alms.npz
  beams_dir: inputs/beams
  rimo_file: inputs/RIMOs/RIMO_HFI_npipe5v16_symmetrized.fits
  pointing:
    input_root: inputs/pointings/processed_od_
    mission_length: full
    use_flag: true
detector_selection:
  channel: null
  detectors:
  - 100-1a
  - 100-1b
  - 100-2a
  - 100-2b
resampling:
  coordinate_system: galactic
nthreads: 0

convolution:
  lmax: 16
  mmax: 6
  epsilon: 1.0e-05
  chunks: 1
map:
  nside: 1024
  nest: false
  output_prefix: full_100_demo_nside1024
output:
  output_dir: outputs
