inputs:
  sky_alm: inputs/sky/notebook_demo_alms.npz
  beams_dir: inputs/beams
  mission_length: full
  pointings: inputs/pointings/pointing_
  flags: inputs/flags/flags_
detector_selection:
  channel: null
  detectors:
  - 100-1a
  - 100-1b
  - 100-2a
  - 100-2b
resampling:
  coordinate_system: galactic
  center_pointing: false
nthreads: 0

convolution:
  lmax: 16
  mmax: 6
  epsilon: 1.0e-05
  chunks: 1
  beam_normalization: unit_integral
map:
  nside: 1024
  nest: false
  use_cross_pol: true
output:
  output_dir: outputs
  output_prefix: full_100_demo_nside1024
