inputs:
  sky_alm: inputs/sky/alms_cmb0000.fits
  beams_dir: inputs/beams
  rimo_file: inputs/RIMOs/RIMO_HFI_npipe5v16_symmetrized.fits
  pointings: inputs/pointings/pointing_
  flags: inputs/flags/flags_
  bad_rings_file: inputs/hfi_bad_intervals.txt
  mission_length: 91-99

detector_selection:
  channel: 100ghz
  detectors: null

resampling:
  coordinate_system: galactic

nthreads: 1

convolution:
  lmax: 1024
  mmax: 6
  epsilon: 1.0e-5
  chunks: 1
  beam_normalization: unit_integral

map:
  nside: 512
  nest: false

output:
  output_dir: outputs
  output_prefix: od91_99_100ghz_nside1024

verbose: true
